### ISSUE TITLE
Post Card Component 제작 및 포스트 등록

### ISSUE THREAD

**Issue by eunnho98** [eunnho98/eunnho98.github.io#2]
## Description
Post page에 삽입할 Post Card 컴포넌트 제작

## To-do
- [ ] 각 포스트 마다 적절한 사진 넣기
- [ ] github.io에 포스트 등록하는 방법 검색
- [ ] 카테고리를 제작 & 카테고리 마다 알맞은 포스트 필터링하는 기능
- [ ] 각 Post hover할 때 animation
